version: '3.8'

services:
  app:
    build: .
    container_name: rekberpay_app
    restart: always
    ports:
      - "8050:8050"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - TOKEN=YOUR_TELEGRAM_BOT_TOKEN
      - MODERATOR_USER_ID=YOUR_TELEGRAM_MODERATOR_ID
      - MYSQL_HOST=host.docker.internal
      - MYSQL_USER=rekberpay_user
      - MYSQL_PASSWORD=user_secure_password_please_change
      - MYSQL_DB=rekberpay_db
      - MYSQL_PORT=3306
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin_secure_password_please_change
      - SHEETY_URL=YOUR_SHEETY_API_URL
      # NOWPayments Gateway settings (can also be configured dynamically inside dashboard settings page)
      - NOWPAYMENTS_API_KEY=YOUR_NOWPAYMENTS_API_KEY
      - NOWPAYMENTS_API_URL=https://api.nowpayments.io
      - NOWPAYMENTS_IPN_SECRET=YOUR_NOWPAYMENTS_IPN_SECRET
      - NOWPAYMENTS_IPN_URL=https://yourdomain.com/webhooks/nowpayments
      - NOWPAYMENTS_EMAIL=YOUR_NOWPAYMENTS_EMAIL
      - NOWPAYMENTS_PASSWORD=YOUR_NOWPAYMENTS_PASSWORD
